### ISSUE TITLE
Composing widgets (which begin with liftEffect)

### ISSUE THREAD

**Issue by jonathanlking** [purescript-concur/purescript-concur-react#10]
If I run `example 1 <> example 2` we get "example1" and "example2" logged to the console, however only the "example2" button is rendered to the DOM.

```
example :: forall a. Int -> Widget HTML a
example x = do
  liftEffect (log $ "example" <> show x)
  _ <- button [onClick] [text $ "example" <> show x]
  example’ x
```

This is not what I expect - I think both buttons should still be rendered. Could you confirm what the correct behaviour should be?

Interestingly moving the logging to _after_ the button click results in both buttons being rendered. I've made [a runnable gist](https://gist.github.com/jonathanlking/49ed254928c64cf861225126202b6e42) that demonstrates this.

**Comment by ajnsit** [comment]
Yeah the current behaviour is buggy. I'm on it.

**Comment by ajnsit** [comment]
Okay @jonathanlking, I think this should be fixed now. It was happening because purescript-aff tries to be helpful and resolves aff actions synchronously whenever possible. I now detect that condition and handle it correctly.

Please let me know if it works for you now. Please feel free to reopen if it doesn't work as expected.

**Comment by jonathanlking** [comment]
Hmm, so running the example from the [gist](https://gist.github.com/jonathanlking/49ed254928c64cf861225126202b6e42) I get both logging, but now neither rendering and a console error: `FAILED! TypeError: Cannot read property 'run' of undefined`

Did you get this example working? Also thanks for responding and working on a fix so quickly, I really appreciate it!

**Comment by ajnsit** [comment]
Weird, I thought I tested it and it was working, but I may have had other code changes which got lost. Reopening this.

**Comment by ajnsit** [comment]
@jonathanlking Can you test out the fix now? I think I now handle the synchronous cases correctly. I also tested the code from your snippet and it seems to work.

**Comment by jonathanlking** [comment]
Yes, it looks good to me now too! Thank you so much for this incredible library and amazing support! 🎉

**Comment by ajnsit** [comment]
Glad to hear it! Thanks for reporting the issue!
