### ISSUE TITLE
liftEffect and liftAff should not change the view

### ISSUE THREAD

**Issue by arthurxavierx** [purescript-concur/purescript-concur-react#12]
Currently, performing effects with `liftEffect`/`liftAff` do cause some flickering in the view, as `asyncAction`/`affAction`/`liftAff` all replace the current view. It should be possible to perform async effects in parallel with widgets that change the view, such as:
```purescript
liftAff someExternalAPICall <|> renderLoader
``` 

It's understandable that there are use cases for `affAction :: v → Aff a → Widget v a`, but it could be implemented as simply as:
```purescript
affAction v aff = do
  display v
  liftAff aff
```

My suggestion is that `liftEffect`/`liftAff` should not be implemented in terms of `affAction`, but instead, the latter should implemented in terms of the former. This enables some interesting and powerful use cases.

**Comment by ajnsit** [comment]
Are you saying that something like `liftAff someExternalAPICall <|> renderLoader` still causes a UI flicker? Then that is certainly a bug.

Also, `affAction v aff` should be equivalent to `display v <|> liftAff aff`, since the view is displayed in parallel to the action.

**Comment by arthurxavierx** [comment]
The routing technique described in https://github.com/ajnsit/purescript-concur/issues/8#issuecomment-393855209 causes some flickering.

**Comment by arthurxavierx** [comment]
I could get routing to work properly with:
```purescript
main :: Effect Unit
main = do
  routes <- AVar.empty
  void $ matches router \_ r ->
    void $ AVar.put r routes mempty

  runWidgetInDom "app" do
    liftAff $ delay (1.0 # Milliseconds)
    awaitRoute routes >>= tailRecM \state ->
      Loop <$> (state <$ app state <|> awaitRoute routes)

  where
    awaitRoute routes = do
      route <- asyncAction mempty $ AVar.read routes
      void $ liftEffect $ AVar.tryTake routes
      pure route
```

Though if I reverse the order of `<|>` to `awaitRoute routes <|> state <$ app state`, the calls to `AVar.take` inside `awaitRoute` never resolve. This is presumably due to previous calls getting resolved first, as it seems that `<|>`/`orr` doesn't cancel the other branches when one of them finishes. Is that a known issue?

Please, feel free to close this issue, as it looks like this was a misunderstanding on my part.

**Comment by ajnsit** [comment]
I'm glad you got it working! I also just finished adding a quick routing example, so you might want to take a look at that as well.

Some comments on your code -
1. You don't need to run the `matches` outside the widget itself (which is bad for modularity). Just use `liftEffect` inside the widget to get the same thing.
2. I'm not sure why you are doing both `read` and `tryTake` inside `awaitRoutes`. `awaitRoutes` should just be defined as `liftAff (take routes)`.

**Comment by ajnsit** [comment]
Here's the code for the Routing example - https://github.com/ajnsit/purescript-concur/blob/master/examples/Test/Routing.purs. Also it shouldn't have any flickering.

**Comment by arthurxavierx** [comment]
Thanks for the comments and the example, it works perfectly!

**Comment by ajnsit** [comment]
Just putting this here for anyone else who stumbled across this issue - I ended up adding a new simple routing example for https://github.com/ajnsit/purescript-concur/issues/12. Here's the [Code](https://github.com/ajnsit/purescript-concur/blob/master/examples/Test/Routing.purs) for the Routing example, and the [demo](https://ajnsit.github.io/purescript-concur/).
