### ISSUE TITLE
Example page is 404

### ISSUE THREAD

**Issue by andys8** [purescript-concur/purescript-concur-react#18]
![Screenshot_20190513-224548](https://user-images.githubusercontent.com/13085980/57652972-0d1b0500-75d1-11e9-8932-e87e8dcc83e1.png)

I think it's because `index.html` in `/docs` is named `index.prod.html`, but shouldn't.

### Not working
https://ajnsit.github.io/purescript-concur/

### Working
https://ajnsit.github.io/purescript-concur/index.prod.html

**Comment by ajnsit** [comment]
Thanks for the report! Fixed in https://github.com/ajnsit/purescript-concur/commit/c0cc87247cd33c68f6c8ba4fe1b5f78267b01d6c.
