### ISSUE TITLE
Map with text doesn't work

### ISSUE THREAD

**Issue by triallax** [purescript-concur/purescript-concur-react#20]
When I try to `map` on an array of strings with `text`, I get an error.

Example:
This doesn't work:
```purs
map text ["foo", "bar", "baz"]
```
But this does:
```purs
map (\s -> text s) ["foo", "bar", "baz"]
```

I'm still unsure about if this is an issue in the PureScript compiler or in Concur.

**Comment by CarstenKoenig** [comment]
not 100% sure but I think this is a case of this issue: https://github.com/purescript/purescript/issues/950

---

if someone wants to see an example of error - for me the eta reduced version produces:

```
  Could not match constrained type
                                               
    LiftWidget (Array ReactElement) t2 => t2 t3
                                               
  with type
         
    t0 t1
         

while trying to match type LiftWidget (Array ReactElement) t2 => t2 t3
  with type t0 t1
while checking that expression (map text) [ "foo"
                                          , "bar"
                                          ]      
  has type Array (t0 t1)
in value declaration main

where t1 is an unknown type
      t0 is an unknown type
      t3 is an unknown type
      t2 is an unknown type
```

**Comment by ajnsit** [comment]
@CarstenKoenig Thanks for the link, yup, it does look like that issue. Though the `LiftWidget` class makes it easy to run into this and I should probably change it.

Keeping the issue open until `map text ["foo", "bar", "baz"]` compiles fine again.

**Comment by ajnsit** [comment]
@MohammedSheikhIbrahim this should be working now. Let me know if it doesn't!

**Comment by triallax** [comment]
I apologize for the late reply.
It is working right now, thanks for your efforts!
Closing this issue.

**Comment by ajnsit** [comment]
Glad to hear it!
