### ISSUE TITLE
Issue with keeping form data in list-view controlled by signals

### ISSUE THREAD

**Issue by bbarker** [purescript-concur/purescript-concur-react#23]
I have the following function, `arrayView`, which is designed to take a signal function of type `(Maybe a -> Signal HTML (Maybe a))` and create an array of such signals (with the ability to add or subtract more of these signals and associated views). In practice, there is a form from concur-formless underlying each `(Maybe a -> Signal HTML (Maybe a))`, though I suppose it might be an issue with fields as well. Whenever I delete or add an item, the issue is that all forms in the array are cleared. This isn't surprising now that I think of it, since none of that transient information is being passwed around:

```purescript

data ItemPersist =
    Delete
  | Keep
derive instance genItemPersist :: Generic ItemPersist _
instance showItemPersist :: Show ItemPersist where
  show = genericShow
instance eqItemPersist :: Eq ItemPersist where
  eq = genericEq

arrayView :: forall a. Int -> (Maybe a -> Signal HTML (Maybe a)) -> Signal HTML (Array a)
arrayView minWidgets mkWidget = D.div_ [] do
  tupArr <- arrayView' initVals
  arrayStr :: String <- pure $ show $ map fst tupArr  -- FIXME: DEBUG
  _ <- display $ D.div' [D.text arrayStr] -- FIXME: DEBUG
  pure $ catMaybes $ map snd tupArr
  where
    emptyElem = Tuple Keep Nothing
    initVals :: Array (Tuple ItemPersist (Maybe a))
    initVals = (1 .. (max 1 minWidgets)) <#> (\_ -> emptyElem)
    mkItemView :: Tuple ItemPersist (Maybe a) -> Signal HTML (Tuple ItemPersist (Maybe a))
    mkItemView item = step item
      case fst item of
        Delete -> mempty
        Keep -> do
          newItem <- D.div' [
            D.li' [dyn $ mkWidget $ snd item]
          , (Tuple Delete $ snd item) <$ D.button [P.onClick] [D.text "Delete"]
          ]
          pure $ mkItemView newItem

    arrayView' :: Array (Tuple ItemPersist (Maybe a)) ->
      Signal HTML (Array (Tuple ItemPersist (Maybe a)))
    arrayView' tupArr = D.div_ [] do
      tupArrP1 <- step tupArr $
        (pure $ snoc tupArr emptyElem) <$ D.button [P.onClick] [D.text "Add item"]
      tupArrNew <- traverse mkItemView tupArrP1
      tupArrFiltered <- pure $ filter (\t -> Keep == fst t) tupArrNew
      pure tupArrFiltered
```

I think probably the appropriate thing to do is to try to use a different approach altogether that doesn't try to re-render all items each time some other item changes.

**Another related issue**: I thought that the expression starting with `tupArrP1 <- step tupArr $` should create a signal, but when i click the "Add item" button, it disappears. 

Incidentally, every time I've tried FRP, it is exactly this sort of dynamic-list management issue that seems to cause issues!

**Comment by bbarker** [comment]
Here's the [branch](https://github.com/labordynamicsinstitute/metajelo-ui/commits/editable_arrays) and [commit](https://github.com/labordynamicsinstitute/metajelo-ui/tree/d605a9badec8f7c3e5f875244c67144a7a4c0338) for the above code (found in `FormUtil.purs`).

Another issue I noticed with this code, is that the line ` tupArrNew <- traverse mkItemView tupArrP1` is not behaving as I expected; it should guarantee that any data that was persisted (that is, it is a `Just` and nothing a `Nothing` in the second tuple entry) is rendered again. However this debug code indicates that is always receives Nothing, even when it has been persisted:

```purescript
      case fst item of
        Delete -> mempty
        Keep -> do
          liftEffect $ logShow $ snd item -- FIXME: DEBUG
```

Also, persisted here just means that the item signal as achieved a non-Nothing value in its return value; it isn't actually being stored anywhere.

**Comment by bbarker** [comment]
In general I think there are two possible, if not necessarily viable, approaches:

1. Pass form state around
2. Pass indices to modify around, and do not re-render untouched indices.

I also wonder what the point of `loopS` is exactly, and if it might help with some of the indicental issues; as stated it "Loop a signal so that the return value is passed to the beginning again", but I thought a signal defined with `step` like the following already achieves this:


```purescript
    mkItemView item = step item
          -- ...
          pure $ mkItemView newItem
 ```

**Comment by bbarker** [comment]
Another problem (there are many! though this is more of a code-smell) with my design above that I already didn't like was the overly-specific type signature. Ideally arrayView would be able to accept something at least as general as `Signal HTML a`, but then a clever, abstract way to still be able to avoid using `catMaybes` would be needed.

**Comment by ajnsit** [comment]
Hi, sorry for the delayed response, I was away on a holiday. I will take a look and get back to you.

**Comment by ajnsit** [comment]
> I also wonder what the point of `loopS` is exactly, and if it might help with some of the indicental issues; as stated it "Loop a signal so that the return value is passed to the beginning again", but I thought a signal defined with `step` like the following already achieves this:

Actually no. State in a `Signal` flows like a waterfall. Effectively, whenever a widget changes, all the "downstream" widgets re-render and lose any transient state. You got it right that if you want to save state from a downstream component, you need to use `loopS` to "pass the state back up".

Do let me know if using `loopS` does not solve your problem!

**Comment by ajnsit** [comment]
> Another problem (there are many! though this is more of a code-smell) with my design above that I already didn't like was the overly-specific type signature. Ideally arrayView would be able to accept something at least as general as `Signal HTML a`, but then a clever, abstract way to still be able to avoid using `catMaybes` would be needed.

Do you mean the signature should be `Int -> (a -> Signal HTML a) -> Signal HTML (Array a)`? Then you would express deletion with returning an `empty` signal? That would work, but would carry a significant overhead with all the `empty`s you would need to carry around.

You could change the signature to be `Int -> (a -> Signal HTML (Maybe a)) -> Signal HTML (Array a)`. I actually don't understand why you need the `Keep` and `Delete` tags, when the `Maybe` is sufficient to indicate that some data item was deleted. I certainly don't think you need to combine the two to get what you currently have in your code as `Tuple ItemPersist (Maybe a)`. What is the difference between `Keep Nothing`, `Delete (Just ...)`, and `Delete Nothing`?

**Comment by bbarker** [comment]
> Actually no. State in a Signal flows like a waterfall. Effectively, whenever a widget changes, all the "downstream" widgets re-render and lose any transient state. You got it right that if you want to save state from a downstream component, you need to use loopS to "pass the state back up".

I think my confusion stems from the difference between e.g. `step` and `loopS`. But after reading up on `step` I can see why it isn't recursive, as it is just an alias for `mkCofree`

On the other hand, in practice, it sometimes seems as though `step` is recursive. Take this simple example:

```purescript
checkBoxS :: Boolean -> Signal HTML Boolean
checkBoxS b = step b do
  newB <- checkBoxW b
  pure $ checkBoxS newB
```

But looking deeper, `checkBoxW` is maintaining its own state (ultimately via the DOM I suppose, or react more directly):

```purescript
checkBoxW :: Boolean -> Widget HTML Boolean
checkBoxW b = not b <$ D.input [P._type "checkbox", P.checked b, P.onChange]
```

To remove this illusion, I can do a minor refactor where the call `checkBoxW b` is factored out of what I had imagined to be a recursive `do` loop (erroneously thought to have been made recursive by `step`), while adding  some logging:

```purescript
checkBoxS :: Boolean -> Signal HTML Boolean
checkBoxS b = step b do
  newB <- checkW
  logShow $ newB
  pure $ checkBoxS newB
  where checkW = checkBoxW b
```

And indeed it works. Sorry for thinking out loud, as it were. If it helps, I can add some summarized version of this to the documentation.

I'll try out `loopS` now.

**Comment by bbarker** [comment]
Actually this still seems recursive in the sense that `checkBoxS` is calling itself, which is a pretty good indication of recursion, and it is calling itself on the updated value of `b` (`newB`)... hmm

**Comment by ajnsit** [comment]
I think the confusion is that Signals are inherently "Widgets + Recursion". However, that's recursion at the Widget level. At the Signal level you have to control any recursion manually.

Recursion at the Widget level means that you can keep showing the same widget after responding to events.

Signals anyways keep displaying the same UI (because the underlying widget is recursive) without any special code. So they are recursive in that sense. However, if you want to loop in the output of a widget to the input of the widget, then you have to use a special combinator like `loopS`.

**Comment by bbarker** [comment]
@ajnsit Thanks for the explanation - I think I see what you mean now, and have started using it internally in `arrayView`.

I pushed a new version to that branch, and it is getting closer. But I think it is currently at a state where it helps answer the question of why I tagged data with `Keep`/`Delete`, see [this line](https://github.com/labordynamicsinstitute/metajelo-ui/blob/editable_arrays/src/Metajelo/FormUtil.purs#L247-L248) for example. 

The data model itself is using `Maybe`, for instance:

```purescript
policySigArray :: Maybe (NonEmptyArray M.InstitutionPolicy) ->
  Signal HTML (Maybe (NonEmptyArray M.InstitutionPolicy))
policySigArray instPoliciesMay = labelSig' D.h2' "Institution Policies" $
  nonEmptyArrayView 1 policySignal
```

Just because something returns `Nothing`, doesn't mean it should be gotten rid of on a subsequent render - the user may still be editing the form, and it won't return a `Just` until they submit.

So I think this means I need to create another layer of `Maybe` around all this - not sure if that's the most elegant solution.

**Comment by bbarker** [comment]
@ajnsit Finally getting back to this more, and made some good progress, especially with using `purescript-option` to manage state of records.

However, I'm not sure how to proceed with `loopS` in this [particular case](https://github.com/labordynamicsinstitute/metajelo-ui/blob/editable_arrays/src/Metajelo/UI.purs#L107-L112):

```purescript
accumulateLocationLoopDebug2 ::  Signal HTML (Maybe NonEmptyString)
accumulateLocationLoopDebug2 = labelSig' D.h1' "Location" $ loopS Nothing \oldNameMay -> D.div_ [] do
  instNameMay <- textInput D.span' "Institution Name: "
  display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
  display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
  pure instNameMay
```

Only `oldNameMay` is ever printed as a non-nothing value. This is fine in this debug situation, but in the actual code, I need to [feed in](https://github.com/labordynamicsinstitute/metajelo-ui/blob/editable_arrays/src/Metajelo/UI.purs#L129-L137) values like this to `newLoc`, so that it may be used as [the new signal value](https://github.com/labordynamicsinstitute/metajelo-ui/blob/editable_arrays/src/Metajelo/UI.purs#L158). I'm not sure how that will work since all the *May values are always nothing in this case.

**Comment by ajnsit** [comment]
Can you give me an example of the output of this? Are you saying that "Old Name" is a `Just` but "New Name" is always `Nothing`? That shouldn't happen.

**Comment by bbarker** [comment]
@ajnsit That's right:

![image](https://user-images.githubusercontent.com/916366/66044423-83bc8e80-e4ef-11e9-8e66-7a614ad2fd40.png)

**Comment by ajnsit** [comment]
Ah now I understand the semantics of `textInput`. It always outputs a `Nothing` to begin with, which effectively resets the state of `instnameMay` to `Nothing`.

With looped signals, you want the feedback to be stable, which means that if a signal outputs a value A, when fed back to itself, it should output A again, and not a different value B, *until a user or a system event happens*.

So to analyse your code step by step -

The initial condition :-

```purescript
  -- oldNameMay is Nothing
  loopS Nothing \oldNameMay -> D.div_ [] do
    -- instNameMay is Nothing
    instNameMay <- textInput D.span' "Institution Name: "
    -- Here oldNameMay is Nothing
    display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
    -- instNameMay is Nothing
    display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
    -- Nothing is returned. This will NOT be looped until a user event happens.
    pure instNameMay
```

User enters "ASDF" in the textbox. This causes the output of `textInput` to change :-

```purescript
  -- oldNameMay is still Nothing
  loopS Nothing \oldNameMay -> D.div_ [] do
    -- instNameMay becomes "ASDF"
    instNameMay <- textInput D.span' "Institution Name: "
    -- Here oldNameMay is Nothing
    display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
    -- instNameMay is "ASDF"
    display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
    -- "ASDF" is returned. The new value is fed back to the top.
    pure instNameMay
```

Immediately, the loop is rerendered with "ASDF". So you never get to see the output of this middle state :-

```purescript
  -- oldNameMay is "ASDF"
  loopS Nothing \oldNameMay -> D.div_ [] do
    -- textInput is rerendered, and outputs Nothing to start
    -- Hence instNameMay is Nothing
    instNameMay <- textInput D.span' "Institution Name: "
    -- oldNameMay is "ASDF"
    display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
    -- instNameMay is Nothing
    display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
    -- Nothing is returned, this will NOT be looped until a user event happens.
    pure instNameMay
```

I hope that explains the behaviour @bbarker. To fix this, you should have the output of `textInput` depend on the input `oldNameMay`. So if `oldNameMay` is `Just something` then the output from `textBox` should also be `Just something` until the user enters some text to override that.

NOTE: You don't necessarily need to change the `textIInput` component itself. I think it would be enough to have `instNameMay` depend on `oldNameMay` after the textInput as well. For example something like -

```purescript
  loopS Nothing \oldNameMay -> D.div_ [] do
    instNameMayEntered <- textInput D.span' "Institution Name: "
    let instNameMay = unwrap (First instNameMayEntered <> First oldNameMay)
    display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
    display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
    pure instNameMay
```

**Comment by bbarker** [comment]
@ajnsit Thanks for the excellent explanation! I wonder if there is a way to change `textInput` so that it doesn't depend on `oldNameMay`, but rather the current value of `D.input`.

I tried several variations using `P.value` and `P.defaultValue`, but no luck as yet.

**Comment by bbarker** [comment]
Well, after sleeping on it, I think the method you described at the end of your last post might be the safest way to wrap these signals in general. Will give that a try.

**Comment by ajnsit** [comment]
> @ajnsit Thanks for the excellent explanation! I wonder if there is a way to change `textInput` so that it doesn't depend on `oldNameMay`, but rather the current value of `D.input`.

Yeah that's the conflict between a controlled and an uncontrolled component in React. You can either control the component and pass around the state manually with something like `oldStateMay`, or you can leave the component uncontrolled, and only have access to the value on event boundaries (such as onChange), not on every rerender. I don't know of a straightforward way to do both.

It might be possible to hack something together with React Refs, where you can get access to the underlying dom node for an input, and then construct a signal which uses the Ref API to always sync to the *current* value of the input element. It would be a nice exercise, and might be a good addition to the library, if it could be shown to be not too buggy.

**Comment by bbarker** [comment]
@ajnsit Regarding the solution you mentioned above, I'm still getting the same behavior in that case (New Name is always `Nothing`):

```purescript
accumulateLocationLoopDebug2 :: Signal HTML (Maybe NonEmptyString)
accumulateLocationLoopDebug2 = loopS Nothing \oldNameMay -> D.div_ [] do
  instNameMayEntered <- textInput D.span' "Institution Name: "
  let instNameMay = unwrap (First instNameMayEntered <> First oldNameMay)
  display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
  display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
  pure instNameMay
```

**Comment by bbarker** [comment]
The original suggestion of modifying textInput seems to work.  In particular,

```purescript
type CtrlSignal v a = a -> Signal v a

textInput'' :: D.El' -> String -> CtrlSignal HTML String
textInput'' tag label initVal = labelSig' tag label $ sig initVal
  where
    sig :: String -> Signal HTML String
    sig txt = step txt do
      newTxt <- D.input [P.unsafeTargetValue <$> P.onChange]
      pure $ sig newTxt
```

(for example). 

`CtrlSignal` is an easily abused abstraction as implemented above, and not that much more concise, but I wonder if this could be improved upon. For now, I will try things along these lines.

**Comment by ajnsit** [comment]
> @ajnsit Regarding the solution you mentioned above, I'm still getting the same behavior in that case (New Name is always `Nothing`):

That is very strange. I just tried a small test example, and I get the behaviour exactly as expected -

```purescript
testWidget :: forall a. Widget HTML a
testWidget = dyn $ loopS Nothing \oldNameMay -> D.div_ [] do
  instNameMay <- textInput Nothing
  -- If I remove the line below, then New Name is always Nothing
  instNameMay <- pure $ unwrap (First instNameMay <> First oldNameMay)
  display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
  display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
  pure instNameMay
  where
  textInput :: Maybe String -> Signal HTML (Maybe String)
  textInput ms = step ms do
    newTxt <- D.input [P.unsafeTargetValue <$> P.onChange]
    pure $ textInput (Just newTxt)
```

Can you try the widget above and let me know if it works as expected for you? If so, then would it be possible for you to give me a small contained sample which shows the problem?

**Comment by bbarker** [comment]
Interesting, I just tried `testWidget`, and my results seem to disagree with your results (i.e., I'm getting the same problem I've been getting all along):

![image](https://user-images.githubusercontent.com/916366/66233481-7ce17780-e6b9-11e9-975c-d58cf873ba2a.png)

**Comment by ajnsit** [comment]
That's really strange. Can you give me the version numbers for the libs you are using? Better still would be if you can host the small sample somewhere so I can just run it.

**Comment by bbarker** [comment]
Hi @ajnsit,

I'll open a new issue for this soon (working on putting a test repo together now). As the original issue is now resolved (hooray!), I think we can close this one at long last.
