### ISSUE TITLE
Update `purescript-react` version

### ISSUE THREAD

**Issue by elliotdavies** [purescript-concur/purescript-concur-react#26]
Hello! `purescript-react` just released `v8.0.0`, which includes updates to the React refs API. I'd like to upgrade the package-set to include this new version but Concur will have to put out an updated release first since it's also in the set :smile: 

As far as I can tell this should just be a case of updating the `ref` prop type [here](https://github.com/ajnsit/purescript-concur/blob/31bb72ba8b226ea8a8d01914cf9bd6eede2f5543/lib/src/Concur/React/Props.purs#L989).

**Comment by ajnsit** [comment]
I have pushed tag `v0.3.9` which uses purescript-react-8.0. Is that all that's needed?

**Comment by elliotdavies** [comment]
@ajnsit Yep that's all! Thanks a bunch.
