### ISSUE TITLE
Using the First semigroup with 

### ISSUE THREAD

**Issue by bbarker** [purescript-concur/purescript-concur-react#30]
As discussed near the end of #23, this is likely due to some version or dependency issues. I created a small test repo at https://github.com/bbarker/concur-ps-debug/ that demonstrates the issue; a live demo can be found at https://bbarker.github.io/concur-ps-debug/

~Unfortunately, I'm having some issues with my account and github pages due to heroku interference that I haven't been able to track down just yet, so to run it for now, it will need to be built locally.~

In more detail, with the specified testWidget code, copied below, I get this effect:

![image](https://user-images.githubusercontent.com/916366/66605893-f3c9b500-eb7e-11e9-9d46-f8e354b37f48.png)

Whereas I should be seeing `New Name` updated as well.  Here is the testWidget:

```purescript
testWidget :: forall a. Widget HTML a
testWidget = dyn $ loopS Nothing \oldNameMay -> D.div_ [] do
  instNameMay <- textInput Nothing
  -- If I remove the line below, then New Name is always Nothing
  instNameMay <- pure $ unwrap (First instNameMay <> First oldNameMay)
  display $ D.div' [D.text $ "Old Name: " <> (show oldNameMay)]
  display $ D.div' [D.text $ "New Name: " <> (show instNameMay)]
  pure instNameMay
  where
  textInput :: Maybe String -> Signal HTML (Maybe String)
  textInput ms = step ms do
    newTxt <- D.input [P.unsafeTargetValue <$> P.onChange]
    pure $ textInput (Just newTxt)
```

**Comment by bbarker** [comment]
An alternative repo + demo URL just in case further issues pop up:
 - Repo: https://github.com/CornellCAC/concur-ps-debug
 - Demo: https://cornellcac.github.io/concur-ps-debug/

**Comment by ajnsit** [comment]
Ah @bbarker I finally see what's wrong with your code! You are using `Semigroup.First`, but you need to use `Maybe.First`. `Semigroup.First` is like `const` in that it always returns its first argument.

To be specific, the difference is -

```purescript
-- Semigroup.First
First x <> _ == First x

-- Maybe.First
First (Just x) <> _ == First (Just x)
First Nothing <> y == y
```

So in your example, you need to change -
`import Data.Semigroup.First (First(..))`
to
`import Data.Maybe.First (First(..))`

Let me know if that works.

**Comment by bbarker** [comment]
Oh, yes, that is definitely the issue. It also seems less mysterious now that I'm looking at the correct `First`!
