### ISSUE TITLE
preact backend

### ISSUE THREAD

**Issue by janat08** [purescript-concur/purescript-concur-react#31]
All 3 of those are lighter by a wide margin, while maintaing same symantics. 200 kb bundle is no good.

**Comment by janat08** [comment]
Apparently preact has a layer for compatibility with react.

**Comment by ajnsit** [comment]
It should be fairly straightforward to create a new backend as long as it has -
1. Purescript bindings
2. A virtual-dom

For libraries that have a virtual-dom already, it's the first part (purescript bindings) which is usually the largest hurdle. Preact is a drop-in replacement for React, so it should be a lot easier to create Purescript bindings for it, if they don't exist already.

Once we have Purescript bindings, I would be happy to help out with any new backend projects, or even build those backends myself.

**Comment by janat08** [comment]
Nerv is probably a better candidate as it's faster and is compatible first, and preact loses speed with used with compatibility layer.

**Comment by ajnsit** [comment]
I'm going to close this, and open an umbrella issue for alternative backends.

**Comment by ajnsit** [comment]
Closing this in favor of the umbrella issue.
