### ISSUE TITLE
update latest version on pursuit

### ISSUE THREAD

**Issue by suzumiyasmith** [purescript-concur/purescript-concur-react#35]
pls.

**Comment by ajnsit** [comment]
I have published v0.4.1 of the library - https://pursuit.purescript.org/packages/purescript-concur-react/0.4.1.
This now depends on purescript-concur-core v0.4.1, which is published in its own package - https://pursuit.purescript.org/packages/purescript-concur-core/0.4.1.

I hope that resolves the issue. Please feel free to reopen if needed.
