### ISSUE TITLE
Mikado backend

### ISSUE THREAD

**Issue by janat08** [purescript-concur/purescript-concur-react#36]
How easy would it be to integrate mikado js as backend. It's really fast, has no synthetic events, and uses plain html5 templates. It's only limitation is that it expects all text to be wrapped in a separate element (no children of element and text)

**Comment by ajnsit** [comment]
It can definitely be done, however I'm unlikely to find time to take it up myself right now. I'll leave this open for a while in case someone else wants to take a look.

**Comment by ajnsit** [comment]
Closing this in favor of the umbrella issue.
