### ISSUE TITLE
Concur for Python

### ISSUE THREAD

**Issue by potocpav** [purescript-concur/purescript-concur-react#37]
I created a [Concur variant for Python](https://github.com/potocpav/python-concur) based on ImGui. The intended use-case is scientific and/or debugging visualizations, rather than user-facing applications. 

It follows the Concur "paradigm" rather closely; the main differences are:

* Everything is synchronous by default and futures must be used explicitly for asynchronous computations. This is because async generators in Python can't return a value.
* Widgets return values wrapped in tuples: `(widget_name, return_value)`. This is because using `<$>` and `<$` equivalents in Python is awkward.

I already found the library useful for several projects.

What do you think about the project? Also, I want to ask whether it's OK for me to use the Concur name and/or logo.

**Comment by ajnsit** [comment]
Excellent! I'm happy to see a python version - the more Concur variants the merrier! You can use the Concur name and logo.

ImgUI was on my radar as a potential Concur target. I'm glad to see that it works well with the paradigm. I will likely use it as a backend for the Haskell version soon.

**Comment by potocpav** [comment]
That was my plan too, but after a while I gave up - FFI was too difficult. Haskell is missing a simple UI library, and Concur + ImGui could fill that gap.

**Comment by ajnsit** [comment]
I've added links to the python version in the main README for all Concur variants.

Closing this issue.
