### ISSUE TITLE
Best way to send window keyboard events to nested widgets?

### ISSUE THREAD

**Issue by mpdairy** [purescript-concur/purescript-concur-react#38]
I would like deeply nested child widgets to be able to react to events that happen in the window or main container. In particular, I need some buttons to react to keyboard events, but I can't just listen for those events at the button level because they require focus to get keyboard events.  I don't see how I could pass the event up to deeply nested children widgets without reloading everything on the way. 

What's the best way to do this?

**Comment by ajnsit** [comment]
@mpdairy I added a keyboard event handling example - https://github.com/purescript-concur/purescript-concur-react/blob/master/examples/src/Test/Keyboard.purs.

This should demonstrate the idiomatic way to handle the specific case of attaching an event handler once and listening to it repeatedly.

In general, for one shot events, there are several non-FFI ways to pass events down to a nested widget without having to rebuild everything. For example, you might want to take a look at -
1. [Remote widgets](https://github.com/purescript-concur/purescript-concur-core/blob/master/src/Concur/Core/Patterns.purs#L48).
2. [Wires](https://github.com/purescript-concur/purescript-concur-core/blob/master/src/Concur/Core/Patterns.purs#L101).
3. [Fork action](https://github.com/purescript-concur/purescript-concur-core/blob/master/src/Concur/Core/Patterns.purs#L65).

None of them are perfect, and have their own tradeoffs. You might want to evaluate each to see which one works for you. They are also just functions implemented on top of the regular widget api, so it's entirely possible to define your own abstractions.

**Comment by ajnsit** [comment]
Closing this. Please feel free to reopen if needed.

**Comment by mpdairy** [comment]
Ok, thanks! This is quite helpful.
