### ISSUE TITLE
Custom Monad for Signals

### ISSUE THREAD

**Issue by drewolson** [purescript-concur/purescript-concur-react#43]
Concur makes it very easy to render Widgets inside of a custom monad stack. Here's a simple example https://gist.github.com/drewolson/0fcff9458d4b36b56e5d7350f7a4d9c7.

However, I'm unable to understand how I'd do the equivalent with Signals. Can I also use Signals inside of a custom monad stack?

**Comment by ajnsit** [comment]
That's a good point! I just checked and there seems to be no reason to not support a more general Signal type. I'll quickly push something for you to test.

**Comment by ajnsit** [comment]
@drewolson Can you try the changes in this branch - https://github.com/purescript-concur/purescript-concur-react/tree/generalised-signals

Specifically, I rewrote the Colors example to use StateT - https://github.com/purescript-concur/purescript-concur-react/blob/generalised-signals/examples/src/Test/Color.purs

**Comment by drewolson** [comment]
It works great! https://gist.github.com/drewolson/c0bf0e72a72e58feb3a4b68a0287c902

**Comment by ajnsit** [comment]
Okay, great. The changes are merged into purescript-concur-core in a backward compatible way. Use `SignalT` when you want to use a monad other than `Widget` inside a signal. `Signal` is aliased to `SignalT (Widget v) a`
