### ISSUE TITLE
Help with composition of signals

### ISSUE THREAD

**Issue by tshakah** [purescript-concur/purescript-concur-react#44]
Hey!

Apologies if this is more of a PureScript question, but I am new to it.

I'm trying to separate out the logic of a complex function, and have managed to write a simple case that explains my issue.

How would you get the following to work (the only difference from the signal example in the concur docs is I've moved `n+1 <$ D.button [P.onClick] [D.text "+"]` to `displayButton`):

```purescript
module Main where

import Prelude

import Concur.Core (Widget)
import Concur.Core.FRP (Signal, display, dyn, loopS, loopW)
import Concur.React (HTML)
import Concur.React.DOM as D
import Concur.React.Props as P
import Effect.Aff (Milliseconds(..), delay)
import Effect.Aff.Class (liftAff)

mainWidget :: forall a. Widget HTML a
mainWidget = do
  dyn $ loopS 0 \n -> do
    display $ D.text (show n)
    n' <- incrementTicker n
    counterSignal n'

-- Counter
counterSignal :: Int -> Signal HTML Int
counterSignal init = loopW init $ \n -> D.div'
  [ displayButton n
  , D.div' [D.text (show n)]
  , n-1 <$ D.button [P.onClick] [D.text "-"]
  ]

displayButton :: Int -> Signal HTML Int
displayButton init = loopW init $ \n -> do
    n+1 <$ D.button [P.onClick] [D.text "+"]

-- Timer
incrementTicker :: Int -> Signal HTML Int
incrementTicker init = loopW init $ \n -> do
  liftAff $ delay $ Milliseconds 1000.0
  pure (n+1)

```

Any help would be appreciated! I've gone through the concur docs a few times and am not sure how to get this to compile.

**Comment by ajnsit** [comment]
`displayButton` is a Signal, so you can't use it inside the `loopW` because `loopW` takes in a Widget (which it invokes repeatedly).

Perhaps you intended to make `displayButton` a Widget? Something like this -

```purescript
displayButton :: Int -> Widget HTML Int
displayButton n =
  n+1 <$ D.button [P.onClick] [D.text "+"]
```

**Comment by ajnsit** [comment]
@tshakah hope that helped. I'm going to close this issue. Please feel free to reopen if you have any more questions.

**Comment by tshakah** [comment]
Yes, it did - thanks! Sorry I didn't respond.
