### ISSUE TITLE
shouldn't the index.js in examples use `./output/Main`? or else live in `dist` dir

### ISSUE THREAD

**Issue by afcondon** [purescript-concur/purescript-concur-react#49]
following the instructions in the README exactly leads you to a Parcel failure because `examples/output` is not one level above `index.js`...works fine if you edit the `index.js` so i guess either you meant to put `examples/index.html` and `examples/index.js` in the `dist` directory?

**Comment by jamievicary** [comment]
I was also caught by this error, which I now see is over a month old. Is this project being actively maintained?

**Comment by ajnsit** [comment]
@jamievicary Yes it is, I've just been a bit busy the past month.

@afcondon I may have broken the examples during a reorganisation. Do you mind submitting a PR that fixes the path? I'll put in a more permanent fix some time later if needed.

**Comment by afcondon** [comment]
sure, i'll try to do it tomorrow morning, @ajnsit

**Comment by ajnsit** [comment]
@afcondon I've merged your fix. Thanks!
