### ISSUE TITLE
Is there anything wrong with creating a signal without using step, loopS, or loopW?

### ISSUE THREAD

**Issue by triallax** [purescript-concur/purescript-concur-react#50]
Is there a case where I might want to use the `do` syntax without any of the functions in the title?

For example, let's say I have `intSignal :: Int -> Signal HTML Int` and `stringSignal :: String -> Signal HTML String`. If I'd want to zip them into a `Tuple Int Signal`, I might use this:
```purs
tupleSignal int str = do
  int' <- intSignal int
  str' <- stringSignal str
  pure $ Tuple2 int' str'
```
Is there anything wrong with doing that?

On a related note, I understand why signals are useful, but I'm having a hard time understanding how to use them well. It still didn't "click" for me. I'd appreciate it if somebody could explain it to me in other words from the official docs.

**Comment by ajnsit** [comment]
Yes, it's perfectly fine to compose Signals using the monad instance.

Signals are conceptually `Never ending Widget + Varying value`. They can be constructed in a number of ways, but the simplest way is using `hold` which has the effective signature `hold :: a -> Widget a -> Signal a`. i.e. it takes an initial value, and a widget that is repeatedly invoked to yield the values of the signal.

Another common way is using `loopW :: a -> (a -> Widget a) -> Signal a` which is similar to `hold`, but passes the previous value into the widget.

For example, let's say we have a "counter" button widget `counterButton :: Int -> Widget Int`, which takes in a current value and then on click of the button returns an incremented count. Then we can create a signal `loopW 0 counterButton` which starts with the number `0` and on each click of the button increments the count. At any point of time the current value can be extracted with `extract`.

Take a look at the other combinators' signatures in https://github.com/purescript-concur/purescript-concur-core/blob/master/src/Concur/Core/FRP.purs. They should give you a good idea of what's possible with Signals

The other important part to signals is composing them monadically. When you compose a sequence of signals in a monad, the net result is a flow like a waterfall. Effectively, whenever a signal changes, all the "downstream" signals re-render (and lose any transient state) and recompute their values. `LoopS` "loops" a monadic flow of signals so when the last signal changes, the value is looped back to the top.

HTH. Please let me know if there are any specific questions.

**Comment by triallax** [comment]
It makes more sense now. I have no further questions. Thanks!
