### ISSUE TITLE
what is the ./stark folder?

### ISSUE THREAD

**Issue by srghma** [purescript-concur/purescript-concur-react#57]
https://github.com/purescript-concur/purescript-concur-react/tree/master/stark

**Comment by srghma** [comment]
it's a "dummy in-memory dom implementation for testing UI applications"

that is not used (yet)

**Comment by ajnsit** [comment]
Yup it's a dummy dom implementation that is largely irrelevant right now as I have rewritten it and will soon release it as a separate library dependent on purescript-concur-core.
