### ISSUE TITLE
add an example with remoteWidget / how to "get data out of a never ending widget" ?

### ISSUE THREAD

**Issue by srghma** [purescript-concur/purescript-concur-react#60]
in documentation

https://ajnsit.github.io/concur-documentation/ch03-03-composing-never-ending-widgets.html

> As the previous section showed, it's recommended to avoid creating widgets which never end, to allow arbitrary composition. However, at this point it must be pointed out that Concur does allow you to compose never-ending widgets in meaningful ways, as long as you remember that a never ending-widget will only be a Consumer, and not a Producer of meaningful data. (PS: There are ways to get data out of a never ending widget as well. See remoteWidget for an example).

could we add this `ways to get data out of a never ending widget as well` as an example?

I dont understand how `remoteWidget` / `forkAction` / `forkActionWithState` functions work

related to https://github.com/purescript-concur/purescript-concur-react/issues/55

**Comment by srghma** [comment]
what the signature means

```
remoteWidget ::
  forall m n a void.
  MonadEffect n =>
  MonadAff m =>
  MonadEffect m =>
  Plus m =>
  m a ->
  n (Tuple (m a) (m void))
```

what is `m a`?

what is `m void`?

**Comment by ajnsit** [comment]
A remote widget essentially splits a widget into two parts, a consumer of user events (`m void`) and a producer of UI updates (`m a`). You would use it to keep the listeners alive while being able to remove the widget from the UI or returning a result from the widget.

I need to write more documentation on these, but the function is short enough for the source to be read. The reason I haven't spent a lot of time writing more documentation for them is that they never felt very satisfactory to me, and I have been looking for better solutions.
