### ISSUE TITLE
toReactClass not exposed

### ISSUE THREAD

**Issue by alenkis** [purescript-concur/purescript-concur-react#66]
Hi, I noticed some of the examples use `toReactClass`, but the releases don't expose this helper, is there a reason for this?

https://github.com/purescript-concur/purescript-concur-react/blob/v0.5.0/src/Concur/React.purs

Thanks!

**Comment by ajnsit** [comment]
Hi, that function is a part of the new Concur rewrite which is still not complete, and you will only find it used in the examples on the main branch. The tagged releases should not (and don't afaict) use this function yet.
