### ISSUE TITLE
Routing Advice

### ISSUE THREAD

**Issue by jeremyjh** [purescript-concur/purescript-concur-react#8]
I read https://github.com/ajnsit/concur/issues/5, but it doesn't really touch on one particular issue, so wanted to ask for advice on it. Its probably boils down to a more general question about how to maintain communication between a callback and the main loop, but these are the particulars:

I've implemented routing using the [PushState](https://pursuit.purescript.org/packages/purescript-routing/7.1.0/docs/Routing.PushState) model offered by `purescript-routing`. Selecting the initial route based on the URL works great - I use their matches function with my case function to map a route to a widget and `runWidgetInDom` on it.

The question has to do with how I respond to routing changes. There is more than one way this could be done in the app; at the moment I am using their `replaceState` based functionality. So a subscribe a listener function created by their `makeInterface`, which is `listen :: (LocationState -> Eff eff Unit)`, and pass their corresponding `pushState` function down to the components that need it (such as the menu or components with anchors).

The problem is what to do inside the `listen` callback. Right now, I just `runWidgetInDom` in it, but this means the whole app is remounted for every nav change.  Since the `eff` can be anything, I could pass an `AVar` down into the listener, and then it can push routing notices to a top level function in the app that loops on it and changes the state.

I could also just return the next route as a normal value from the widgets either directly or in a StateT, and push only to update the browser's location bar. 

edit: Actually I figured out the react warning was my own bug, I was actually mounting twice on every change; edited that part of the text.

**Comment by ajnsit** [comment]
Concur provides async support through the magical purescript-aff library. So all you really need to do is convert any listening functions into Aff actions. There will be some adapters required for handling Cancelers etc., but the good thing is that the listener will be automatically canceled when the widget ends.

I went ahead and wrote some code for purescript-routing, but I haven't tested it (just checked that it typechecks) -

```haskell
-- I should add this function to Concur.Core
asyncAction v handler = affAction v (makeAff (map effCanceler <<< handler))

-- A widget that listens for route changes
awaitRoute :: Widget HTML MyRoutes
awaitRoute = asyncAction mempty (matches myRoute <<< handler)
  where handler callback = \_ newRoute -> callback (Right newRoute)
```

Do let me know if this works! I would be happy to add a routing example to the repo.

**Comment by jeremyjh** [comment]
Thanks this is really helpful!  I did not notice `affAction`. 

This did work, it needed a small modification for version 7.1.0 of purescript-routing which I'm pinned too at the moment by other dependencies.

One curious thing that gave me some trouble, is that if `awaitRoute` is the first thing we do in a Widget computation then there will be issues mounting widgets (react warning and nothing mounts). If we do some other action first then its ok; I found just adding a 1 ms delay at the top of the loop would solve it.

```purescript
main = do
  nav <- makeInterface
  runWidgetInDom "app" $ forever $ do
    liftAff (delay (Milliseconds 1.0))
    route <- awaitRoute nav
    log $ "dispatching route: " <> show route
    dispatch route nav
``` 

eta: this is the version that works with 7.1.0

```purescript
awaitRoute nav = do
  asyncAction mempty  (\action -> (matches maybeRoute <<< handler) action nav)
  where handler callback = \_ newRoute -> callback (Right newRoute)
```

**Comment by ajnsit** [comment]
Glad to hear it! I'll add `asyncAction` to Concur.Core, and will add a routing example when I get the time.

**Comment by ajnsit** [comment]
Added `asyncAction` to Concur.Core here - https://github.com/ajnsit/purescript-concur/commit/3d70fca25b05b74898d09ea36c647efdae40b485

**Comment by ajnsit** [comment]
@jeremyjh I also fixed your issue with needing a delay before `awaitRoute`. See my commit - https://github.com/ajnsit/purescript-concur/commit/f82da5fa1bbe8aa52cc159d7946779ac5c221a9c. And also this response from purescript-aff folks- https://github.com/slamdata/purescript-aff/pull/57#issuecomment-393810406.

**Comment by jeremyjh** [comment]
I've ended up using a little different approach. I'm not sure everyone wants this, but the behavior I'd like is that when a new route is pushed, the new widget tree is rendered even if the current one does not terminate itself.  `purescript-concur` actually makes this really elegant! I leave the matches callback running and putting each new result into an AVar. In my main loop I block on a takeVar <|> currentRoute - so current route is shown until a new route arrives.  This is my complete main function, does this look sound?

```purescript
main = do
  nav <- makeInterface
  let routePusher = nav.pushState (toForeign {})
  let context = AppContext { routePusher }
  routeVar <- makeEmptyVar
  void $ nav # matches maybeRoute (routeCallback routeVar)
  runWidgetInDom "app" $ do
    liftAff (delay (Milliseconds 1.0))
    route <- awaitRoute routeVar
    tailRecM loop {context, route, routeVar}
  where
    loop args@{context, route, routeVar} = do
      newRoute <- awaitRoute routeVar <|> route <$ dispatch context route
      pure $ Loop args {route = newRoute}
    routeCallback routeVar _ newRoute =
      void $ putVar newRoute routeVar (const $ pure unit)
    awaitRoute routeVar = affAction mempty $ takeVar routeVar
    dispatch context Nothing = flip runReaderT context menu
    dispatch context (Just route) = flip runReaderT context $
      case route of
        UserIndex -> userIndex
        _ -> menu
```

**Comment by ajnsit** [comment]
Just putting this here for anyone else who stumbles across this issue - I ended up adding a new simple routing example for https://github.com/ajnsit/purescript-concur/issues/12. Here's the [Code](https://github.com/ajnsit/purescript-concur/blob/master/examples/Test/Routing.purs) for the Routing example, and the [demo](https://ajnsit.github.io/purescript-concur/).
